/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RandJLawFirm;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableModel;

/**
 *
 * @author iijoo
 */
public class DeleteClient extends javax.swing.JFrame {

    int index = -1;

    public void TableContent() throws FileNotFoundException {

        // Set Table Rows and Columns Sizes
        ClientsInformation.setRowHeight(20);
        TableColumnModel columnModel = ClientsInformation.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(50);
        columnModel.getColumn(1).setPreferredWidth(50);
        columnModel.getColumn(2).setPreferredWidth(10);
        columnModel.getColumn(3).setPreferredWidth(60);
        columnModel.getColumn(4).setPreferredWidth(50);
        columnModel.getColumn(5).setPreferredWidth(100);
        columnModel.getColumn(6).setPreferredWidth(130);
        // declare table variable to start fill the table with clients information
        DefaultTableModel ClientsTable = (DefaultTableModel) ClientsInformation.getModel();
        // clear table from any values 
        ClientsTable.setRowCount(0);
        // fill clients arraylist
        Client.ReadInformations();
        // insert clients information into the table 
        for (int i = 0; i < Client.Clients.size(); i++) {
            Vector row = new Vector();
            row.add(Client.Clients.get(i).getFirstName());
            row.add(Client.Clients.get(i).getLastName());
            row.add(Client.Clients.get(i).getGender());
            row.add(Client.Clients.get(i).getPhone());
            row.add(Client.Clients.get(i).getSSN());
            row.add(Client.Clients.get(i).getEmail());
            row.add(Client.Clients.get(i).getBankIBAN());
            ClientsTable.addRow(row);
        }

    }

    public DeleteClient() throws FileNotFoundException {
        initComponents();
        TableContent();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ClientsInformation = new javax.swing.JTable();
        Delete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Clients ");

        ClientsInformation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First Name", "Last Name", "Gender", "Phone Number", "SSN", "Email", "Bank Account Number"
            }
        ));
        ClientsInformation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClientsInformationMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(ClientsInformation);

        Delete.setText("Delete Client");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 741, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(372, 372, 372)
                        .addComponent(Delete)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addComponent(Delete)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ClientsInformationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClientsInformationMouseClicked
        index = ClientsInformation.getSelectedRow();
    }//GEN-LAST:event_ClientsInformationMouseClicked

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        try {
            if (index == -1) { 
                // In case user press "delete" button while user didn't choose client to delete
                JOptionPane.showConfirmDialog(null,
                        "You Did Not Select Client to Delete",
                        "Select Client", JOptionPane.DEFAULT_OPTION,
                        JOptionPane.INFORMATION_MESSAGE);
            } else {
                int choice = JOptionPane.showConfirmDialog(null,
                        "Are you Sure You Want to Delete " + Client.Clients.get(index).getFirstName() + " "
                        + Client.Clients.get(index).getLastName() + " ?",
                        "Confirm Client Deletion", JOptionPane.YES_NO_OPTION,
                        JOptionPane.ERROR_MESSAGE);
                
                if (choice == JOptionPane.YES_OPTION) {
                    // delete from the file "Our Database"
                    Client.DeleteClientInformationOnDB(index * 7);
                    // delete from the arraylist
                    Client.Clients.remove(index);
                    // set all things back
                    index = -1;
                    TableContent();
                }
                if (choice == JOptionPane.NO_OPTION) {
                    // user don't want to delete the client
                    // set all things back
                    index = -1;
                    TableContent();
                }

            }

        } catch (IOException ex) {
            Logger.getLogger(DeleteClient.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_DeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new DeleteClient().setVisible(true);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(DeleteClient.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ClientsInformation;
    private javax.swing.JButton Delete;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
